require_relative "../decrypt.rb"

describe  "#decrypt" do
  it "returns an empty string when passed an empty string" do
    actual = decrypt("")
    expected = ""
    expect(actual).to eq(expected)
  end

  it "returns the 3-letter forward-shifted text" do
    actual = decrypt("FK ZOVMQLDOXMEV, X ZXBPXO ZFMEBO, XIPL HKLTK XP ZXBPXO'P ZFMEBO, QEB PEFCQ ZFMEBO, ZXBPXO'P ZLAB LO ZXBPXO PEFCQ, FP LKB LC QEB PFJMIBPQ XKA JLPQ TFABIV HKLTK BKZOVMQFLK QBZEKFNRBP. FQ FP X QVMB LC PRYPQFQRQFLK ZFMEBO FK TEFZE BXZE IBQQBO FK QEB MIXFKQBUQ FP OBMIXZBA YV X IBQQBO PLJB CFUBA KRJYBO LC MLPFQFLKP ALTK QEB XIMEXYBQ. CLO BUXJMIB, TFQE X IBCQ PEFCQ LC 3, A TLRIA YB OBMIXZBA YV X, B TLRIA YBZLJB Y, XKA PL LK. QEB JBQELA FP KXJBA XCQBO GRIFRP ZXBPXO, TEL RPBA FQ FK EFP MOFSXQB ZLOOBPMLKABKZB.")
    expected = "IN RYPTOGRPHY,  ESR IPHER, LSO KNOWN S ESR'S IPHER, THE SHIFT IPHER, ESR'S ODE OR ESR SHIFT, IS ONE OF THE SIMPLEST ND MOST WIDELY KNOWN ENRYPTION TEHNIQUES. IT IS  TYPE OF SUSTITUTION IPHER IN WHIH EH LETTER IN THE PLINTEXT IS REPLED Y  LETTER SOME FIXED NUMER OF POSITIONS DOWN THE LPHET. FOR EXMPLE, WITH  LEFT SHIFT OF 3, D WOULD E REPLED Y , E WOULD EOME , ND SO ON. THE METHOD IS NMED FTER JULIUS ESR, WHO USED IT IN HIS PRIVTE ORRESPONDENE."
    expect(actual).to eq(expected)
  end
end
